#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

define('LARAVEL_INSTALLER_PATH', __DIR__);
define('CACHE_PATH', __DIR__ . DIRECTORY_SEPARATOR . 'cache');

$app = new Symfony\Component\Console\Application('Laravel Installer', '2.3.0');
$app->add(new Laravel\Installer\Console\NewCommand);
$app->add(new Laravel\Installer\Console\CacheCommand);
$app->add(new Laravel\Installer\Console\VersionsCommand);

$app->run();
